# Generated by Django 3.0.3 on 2021-01-30 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_company', models.CharField(max_length=50, null=True)),
                ('vendor_name', models.CharField(max_length=50, null=True)),
                ('PO_Number', models.CharField(max_length=50)),
                ('PO_Date', models.DateField()),
                ('description', models.TextField(max_length=250, null=True)),
                ('rate', models.FloatField()),
                ('Qty', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Tax', models.FloatField()),
                ('Total', models.FloatField(blank=True, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Product')),
                ('Vendor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Vendor')),
            ],
            options={
                'verbose_name_plural': 'purchaseOrder',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_company', models.CharField(max_length=20, null=True)),
                ('customer_name', models.CharField(max_length=20, null=True)),
                ('Invoice_number', models.CharField(max_length=30)),
                ('Invoice_date', models.DateField()),
                ('payment_terms', models.TextField(max_length=250, null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('rate', models.FloatField()),
                ('Qty', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Tax', models.FloatField()),
                ('Total', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Customer')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'invoice',
            },
        ),
    ]
