# Generated by Django 3.0.3 on 2021-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, max_length=300)),
                ('ticket_no', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(blank='False', max_length=100, null='False')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MODERATE', 'Moderate')], default='', max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('IN PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=200, null=True)),
                ('solution_details', models.CharField(max_length=200, null='True')),
            ],
            options={
                'verbose_name_plural': 'SLA',
            },
        ),
    ]
