# Generated by Django 3.0.3 on 2021-01-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210130_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='upload_documents',
            field=models.FileField(null=True, upload_to='static'),
        ),
    ]
