# Generated by Django 3.0.3 on 2021-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210130_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='upload_documents',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
