# Generated by Django 3.0.3 on 2021-02-25 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0009_auto_20210201_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('project_deadline', models.DateField()),
                ('owner', models.CharField(max_length=100)),
                ('project_status', models.CharField(choices=[('PLANNING', 'Planning'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing'), ('DEPLOYMENT', 'Deployment'), ('COMPLETED', 'Completed')], default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_link', to='ProjectManagement.Project')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='authentication.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assigned', models.CharField(default='', max_length=100)),
                ('updates', models.CharField(default='', max_length=100)),
                ('task_deadline', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.Team')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.EmployeeProfile')),
            ],
            options={
                'verbose_name_plural': 'Team Member',
            },
        ),
        migrations.CreateModel(
            name='Businessopportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('contact_person', models.CharField(default='', max_length=100)),
                ('email_id', models.EmailField(default='', max_length=100)),
                ('phone_no', models.CharField(default='', max_length=100)),
                ('additional_contact', models.CharField(default='', max_length=300, null='False')),
                ('details', models.CharField(max_length=300, null='False', verbose_name='')),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('followup_date', models.DateField()),
                ('followup_message', models.TextField(default='', max_length=150)),
                ('upload_documents', models.FileField(blank=True, upload_to='')),
                ('responsible_person', models.ManyToManyField(to='authentication.EmployeeProfile')),
            ],
            options={
                'verbose_name_plural': 'Business Opportunity',
            },
        ),
    ]
