# Generated by Django 3.0.3 on 2021-02-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210201_0950'),
        ('ProjectManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamManagement',
            new_name='TeamMember',
        ),
    ]
