# Generated by Django 3.0.3 on 2021-02-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManagement', '0002_auto_20210225_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='task_assigned',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='task_deadline',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='updates',
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_assigned', models.CharField(default='', max_length=100)),
                ('updates', models.CharField(default='', max_length=100)),
                ('task_deadline', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManagement.TeamMember')),
            ],
            options={
                'verbose_name_plural': 'Team Member',
            },
        ),
    ]
